### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Lenni0451** [RyDog199/ACNL-NTR-Cheats#14]
After Launching ACNL the 3Ds get stuck at the Bootscreen of the Game. I have to hold down the Power Button to turn the 3Ds off. I'm using Luma3Ds 11.0.0.33E and the European version of the game and cheat Plugin.

Edit: Im doing this on a New 3Ds

**Comment by RyDog199** [comment]
Are you sure your save isn't corrupted? I don't think theres any codes that would crash your game on boot like that... 
Boot your game without NTR and tell me if you can start up your save normally.

**Comment by SirBeethoven** [comment]
Hmm, yeah, try booting without NTR. If it is still crashed by then, you should restore a backup from before you noticed this (and backup this save too just in case)

**Comment by Lenni0451** [comment]
I booted the game without NTR an everything is working. I think the problem is not that I'm using the Eshop version

**Comment by Lenni0451** [comment]
Ok, the Problem is fixed. I used an outdated version of NTR.
But now the cheat is not loading and the normal NTR menu is showing up when pressing Y + X

**Comment by Lenni0451** [comment]
Ok, I'm stupid. I should read the Instructions. I pressed Y+X and not SELECT what you should press. but now everything is working.

**Comment by SirBeethoven** [comment]
Good Good! If you have any more questions, read the forum :)
