### ISSUE TITLE
Tree Stump Ghosting

### ISSUE THREAD

**Issue by TotoroMeats** [RyDog199/ACNL-NTR-Cheats#15]
I was playing with a friend online using the coordinates modifier, when I somehow broke a tree stump in the process. I sat down on it and started to edit all around town then got back up to walk normally. When we got back to the stump, we couldn't sit on it and if we tried to dig it up, it would send you in the "missed" animation like if you were trying to use the shovel off a cliff.

**Comment by RyDog199** [comment]
That is called desync. You illegally got off of the stump so your game thinks the stump is empty but since you didn't get off the stump legally, the server thinks the stump is occupied. This can be easily fixed by refreshing the town by saving or going inside/outside
