### ISSUE TITLE
the 3ds say error and reboot after green screen

### ISSUE THREAD

**Issue by Xyphoseos** [RyDog199/ACNL-NTR-Cheats#18]
after launch ntr 3.4

I launch ACNL, the green screen appeared 

And my N3DS crash 

and he say "an error ... The console go to reboot"...

help me please

**Comment by SirBeethoven** [comment]
Try relaunching, what happens? It might just be a NTR problem

**Comment by Wizzo125** [comment]
I have the same problem, I have the EUR game and I'm on o3DS, launching ntr 3.3 (same result for other versions), launching ACNL, green screen, then the error message and that the console needs to reboot.
