### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by Arch9SK7** [RyDog199/ACNL-NTR-Cheats#29]
When using the Special NPC Mod on the latest release (specifically the K.K. Slider (I didn't try others) NPC)
Then head into the street portion of town it crashes the game and console. This was done in my own town.

**Comment by RyDog199** [comment]
Main street or the Happy Home street? I can't really reproduce this crash...

**Comment by Arch9SK7** [comment]
It was on the Main Street. It is possible I might have had another code on that I was not aware of though.

**Comment by Khanhlinhrainbow** [comment]
If you turn on the text to item, real time edit, and nook times for free cheats,
and go into retail, it gets stuck at the loading train forever and you have to shut down or exit the game.
I tried it twice to be sure :)

**Comment by sandhoners123** [comment]
This should be in a different issue

**Comment by Slattz** [comment]
Since this issue occurred in a very old version of the plugin, I will be losing the issue. Feel free to repost if the issue still occurs on the latest version of the plugin.
