### ISSUE TITLE
Water all flowers custom item tag

### ISSUE THREAD

**Issue by thaleskpl** [RyDog199/ACNL-NTR-Cheats#34]
Which cheat isn't working: Water all flowers (R+A)
Version of the plugin: 3.2.1
Version of NTR: 3.4 from bootNTR selector
New or old 3ds: Old 3ds
System Version: 11.4.0
CFW used: Luma3ds
Version of game: 1.5 (Welcome amiibo update)
Type of game: Legit cart
Describe your method of trying to get the cheat working: I don't know if it's intended of if this is a bug,  but when I use the water all flowers code in my town, it removes their custom tags and they spot acting as hybrids, giving only the white variant of the flowers species.

I tried searching for this issue on the gbamtep thread, but couldn't find any post about it.

**Comment by Slattz** [comment]
Since this issue occurred in a very old version of the plugin, I will be closing the issue. Feel free to repost if the issue still occurs on the latest version of the plugin.
