### ISSUE TITLE
"Grow All Trees" + Save = Death of game

### ISSUE THREAD

**Issue by ebflover777** [RyDog199/ACNL-NTR-Cheats#37]
Ok, so I used the hack, planted a ton of bamboo shoots, pressed x, and saved. When I went back outside, the console crashed. I tried loading the game but it crashed on bootup. As a result, I had to delete both the save data and 1.5. I should have restored or backed up the data, but I have no idea on how to properly do that because I am new to the hacking community.

**Comment by RyDog199** [comment]
Could you send me the save or is it already long gone?
Perhaps you used more codes other than that one, but I'm not sure...

**Comment by RyDog199** [comment]
Closing this as the reporter failed to give more details to track the issue.
