### ISSUE TITLE
Multiplayer fatal crash with infinite wallet bells enabled

### ISSUE THREAD

**Issue by DeityofSwA** [RyDog199/ACNL-NTR-Cheats#38]
I know this one is minor and a lot of people may not use it, but I discovered that having that enabled makes ending an online session or leaving a town immediately fatal crash. I know it's not another code, because I enable everything I usually do except for that code when I go online now, and I never fatal crash.

**Comment by RyDog199** [comment]
Will be fixed in 4.0 as we now have the decryption/encryption function for bells.
