### ISSUE TITLE
Text To Item , Real Time Edit and some others

### ISSUE THREAD

**Issue by captiantwinkie** [RyDog199/ACNL-NTR-Cheats#40]
i want to do text to item but it doesnt work , when i send the item id into chat and press X+D pad right , it just shuts off the code and real time edit just doesnt wanna work but after a while the item spawns in

**Comment by Slattz** [comment]
Since this issue occurred in a very old version of the plugin, I will be closing the issue. Feel free to repost if the issue still occurs on the latest version of the plugin.
