### ISSUE TITLE
Water All Flowers Issue #2

### ISSUE THREAD

**Issue by HanaYakoshi** [RyDog199/ACNL-NTR-Cheats#43]
Which cheat isn't working: Water all flowers (R+A)
Version of the plugin: 3.3?
Version of NTR: 3.6 from bootNTR selector
New or old 3ds: Old 3ds
System Version: 11.5.0
CFW used: Luma3ds
Version of game: 1.5 (Welcome amiibo update)
Type of game: Legit cart
Describe your method of trying to get the cheat working: I first want to say having this feature back is really helpful and would rather have this than nothing at all. Its a very small issue. When i went to water flowers with R+A i did use the (marcrobledo) editor after for something and found some objects in my house and museum have been named watered and also buried as well as random and empty, nameless spaces (may of also fiddled with something to do with naming fossils but unsure if i did that right to even work).

Just wanted to bring the issue up just in case!

**Comment by Slattz** [comment]
Since this issue occurred in an old version of the plugin (3.3), I will be closing the issue. Feel free to repost if the issue still occurs on the latest version of the plugin.
