### ISSUE TITLE
Does this work on the Welcome Amiibo update

### ISSUE THREAD

**Issue by sandhoners123** [RyDog199/ACNL-NTR-Cheats#48]
Before trying this, I want to know whether this cheat works on Welcome Amiibo

**Comment by rctgamer3** [comment]
Yes.

**Comment by Slattz** [comment]
It currently only works on ACNL that **doesn't** have Welcome Amiibo preinstalled.
If your game's icon looks like [this](http://bit.ly/ACNL-Icon), and you have version 1.5 installed, it will work.
