### ISSUE TITLE
OSD couldn't be installed: #2!

### ISSUE THREAD

**Issue by Lenni0451** [RyDog199/ACNL-NTR-Cheats#50]
**Issue:**

When I start AC:NL a window shows up saying "OSD couldn't be installed: #2!".
Then the game starts normally and the cheats do not work.

**Version of plugin:**

4.0 Beta 3

**NTR Version used:**

NTR v3.6

**Type of 3DS:**

New 3DS

**3DS Firmware Version:**

11.6.0-39E

**CFW on 3DS:**

Luma3DS

**ACNL Version:**

Original ACNL with the v1.5 update

**Source of game:**

eShop Download

**Language & Region:**

German & Europe

**Extra description of event:**

Everything should be said.

**It is also recommended to send us a luma crash dump.
The crash dump will be located at `SD:/luma/dumps/arm11` or `SD:/luma/dumps/arm9`.**

No crash. Just does not work.

**Comment by Slattz** [comment]
@Lenni0451 This is because you have another plugin in the folder. Delete it and 4.0 should work.

**Comment by Lenni0451** [comment]
Thanks. That worked. I had the Clock Plugin enabled.
