### ISSUE TITLE
My Save Data Is Corrupted

### ISSUE THREAD

**Issue by 8bluefish** [RyDog199/ACNL-NTR-Cheats#51]
Save Data Corrupted
My Save Data is Gone

**Version of plugin:**

 4.0 Beta 3

**NTR Version used:**

NTR v3.6

**Type of 3DS:**

 New 3DS,

**3DS Firmware Version:**
Sys 11.6.0-39U
**CFW on 3DS:**
 Luma3DS, 

**ACNL Version:**

 Original ACNL with Update

**Source of game:**
 Cart
**Language & Region:**

. English 

**Extra description of event:**

my save data got corrupted i made a backup when it asked me to but idk how to get my backup back years of progress is all gone!!!

**Comment by Slattz** [comment]
Is it corrupt or do you get a crash screen with a bunch of numbers on it?

**Comment by 8bluefish** [comment]
I fixed it i had to put my my garden_new.dat in acnl save editor and change the secure value and inject the save with checkpoint

**Comment by Slattz** [comment]
Alright, cool.
